--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BedrockPlay/BasicEssentials
build-by-default: true
branches:
- master
projects:
  BasicEssentials:
    path: ""
    libs:
      - src: BedrockPlay/OpenAPI/OpenAPI
...
